# Generated by Django 4.1.7 on 2023-08-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworld', '0016_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent_category',
            new_name='category',
        ),
    ]
