# Generated by Django 4.1.7 on 2023-08-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworld', '0017_rename_parent_category_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
